name: getZhihu-Action

on:
  watch:
    types: [started]
  schedule:
    - cron: "0 0 * * *"
    - cron: "0 4 * * *"
    - cron: "0 8 * * *"
    - cron: "0 12 * * *"
    - cron: "0 16 * * *"
    - cron: "0 20 * * *"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Get Zhihu
      run: |
        python ZhihuRun.py
      
    - name: Commit
      run: |
        git config --global user.email 88888@163.com
        git config --global user.name github
        git add .
        git commit -m "成功获取知乎并Push" -a
        git push

